COMP: Update Slicer and VTK to workaround pthread and dl link errors
List of Slicer updates:

$ git shortlog f81033d29c..008c30e7fe --no-merges
Jean-Christophe Fillion-Robin (1):
      [cell-locator] COMP: Update VTK to workaround pthread and dl link errors

-----
List of VTK updates:

$ git shortlog 97904fdcc7..925473c4fb --no-merges
Jean-Christophe Fillion-Robin (2):
      COMP: Remove FindTBB and expect VTK to be configured with TBB_DIR
      COMP: Workaround pthread and dl link errors when VTK_ENABLE_KITS is ON

-----
This commit workarounds the following link errors reported when using
gcc 9.4.0 (Ubuntu 20.04).

[100%] Linking CXX executable ../../bin/vtkProbeOpenGLVersion
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_setspecific'
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_getspecific'
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_key_create'
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_mutexattr_settype'
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_mutexattr_init'
../../lib/libvtkexodusII-8.2.so.1: error: undefined reference to 'pthread_once'
../../lib/libvtkhdf5-8.2.so.1: error: undefined reference to 'dlerror'
../../lib/libvtkhdf5-8.2.so.1: error: undefined reference to 'dlsym'
../../lib/libvtkhdf5-8.2.so.1: error: undefined reference to 'dlopen'
../../lib/libvtkhdf5-8.2.so.1: error: undefined reference to 'dlclose'